hook test

diff --git a/.githooks/post-checkout b/.githooks/post-checkout
--- a/.githooks/post-checkout
+++ b/.githooks/post-checkout
@@ -1,23 +1,27 @@
 #!/bin/bash
 
-source .env
+echo "arg1: '$1'"
+echo "arg1 length: ${#1}"
 
-mapfile -t sensitive < <(aws s3 ls s3://$PRIVATE_S3_BUCKET/dev --recursive | awk '{print $4}')
+# source .env
 
-paths=$(echo ${sensitive[@]} | sed "s|dev/||g")
+# mapfile -t sensitive < <(aws s3 ls s3://$PRIVATE_S3_BUCKET/dev --recursive | awk '{print $4}')
 
-if [ $? -eq 0 ]; then
-    echo "Getting mandatory files..."
-    for i in "${!sensitive[@]}"; do
-        download_output=$(aws s3 cp s3://$PRIVATE_S3_BUCKET/${sensitive[$i]} $paths[i])
-        if [ $? -eq 0 ]; then
-            echo "Got ${paths[$i]}!"
-        else
-            echo "Error for ${paths[$i]}!"
-            echo $download_output
-        fi
-    done
-else
-    echo "Fetching files from S3 failed!"
-    exit 1
-fi
+# paths=$(echo ${sensitive[@]} | sed "s|dev/||g")
+
+# if [ $? -eq 0 ]; then
+#     echo "Getting mandatory files..."
+#     for i in "${!sensitive[@]}"; do
+#         download_output=$(aws s3 cp s3://$PRIVATE_S3_BUCKET/${sensitive[$i]} $paths[i])
+#         if [ $? -eq 0 ]; then
+#             echo "Got ${paths[$i]}!"
+#         else
+#             echo "Error for ${paths[$i]}!"
+#             echo $download_output
+#         fi
+#     done
+# else
+#     echo "Fetching files from S3 failed!"
+#     exit 1
+# fi
+
